// build.rs — No longer needed for UniFFI proc-macro approach.
// The scaffolding is generated by `uniffi::setup_scaffolding!()` in lib.rs.
fn main() {
    // Nothing to do — proc-macro UniFFI does not need build.rs scaffolding.
}